"""add personnel.username & password_hash

Revision ID: 3de4aa5a98e5
Revises: ca81aa765961
Create Date: 2025-05-08 06:45:58.285741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de4aa5a98e5'
down_revision = 'ca81aa765961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
