"""add password_hash to personnel

Revision ID: d4c4ecde4248
Revises: 3de4aa5a98e5
Create Date: 2025-05-08 15:09:49.037320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c4ecde4248'
down_revision = '3de4aa5a98e5'
branch_labels = None
depends_on = None


def upgrade():
  op.add_column('personnel',
    sa.Column('password_hash', sa.String(length=128), nullable=False, server_default=''))
op.alter_column('personnel', 'password_hash', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
